FROM node:26-alpine@sha256:e71ac5e964b9201072425d59d2e876359efa25dc96bb1768cb73295728d6e4ea AS base

# Install dependencies only when needed
FROM base AS deps

COPY . /app
WORKDIR /app

RUN apk add --no-cache python3 py3-pip

# Create and activate virtual environment, then install Python dependencies
RUN if [ -f server/python/requirements.txt ]; then \
  python3 -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --no-cache-dir -r server/python/requirements.txt; \
  fi

# Make sure the virtual environment is in PATH
ENV PATH="/opt/venv/bin:$PATH"

RUN npm install -g corepack --force && corepack enable
RUN corepack pnpm install

FROM deps AS runner

WORKDIR /app

CMD ["pnpm", "dev"]
