name: streamarr

services:
  streamarr:
    container_name: streamarr-dev
    build:
      context: .
      dockerfile: Dockerfile.local
    image: streamarr-dev:latest
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
