FROM node:26-alpine@sha256:aadf416b2cdce311a8811ba3f0608a61b77dbf997500e2eafe781b51f6a0b019 AS base

# Install dependencies only when needed
FROM base AS deps

COPY . /app
WORKDIR /app

RUN npm install -g corepack --force && corepack enable
RUN corepack pnpm install

FROM deps AS runner

WORKDIR /app

CMD ["pnpm", "dev"]
