FROM node:26-alpine@sha256:725aeba2364a9b16beae49e180d83bd597dbd0b15c47f1f28875c290bfd255b9 AS base

# Install dependencies only when needed
FROM base AS deps

COPY . /app
WORKDIR /app

RUN apk add --no-cache python3 py3-pip

# Create and activate virtual environment, then install Python dependencies
RUN if [ -f server/python/requirements.txt ]; then \
  python3 -m venv /opt/venv && \
  . /opt/venv/bin/activate && \
  pip install --no-cache-dir -r server/python/requirements.txt; \
  fi

# Make sure the virtual environment is in PATH
ENV PATH="/opt/venv/bin:$PATH"

RUN npm install -g corepack --force && corepack enable
RUN corepack pnpm install

FROM deps AS runner

WORKDIR /app

CMD ["pnpm", "dev"]
