allowBuilds:
  bcrypt: true
  cypress: true
  sharp: true
  sqlite3: true
  '@parcel/watcher': false
  '@scarf/scarf': false
  esbuild: false
  unrs-resolver: false
overrides:
  eslint-config-next>typescript-eslint: ^8.58.2
