/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import comments from "strapi-plugin-comments/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import timezoneSelect from "strapi-plugin-timezone-select/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-versioning": contentVersioning,
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    comments: comments,
    "config-sync": configSync,
    "duplicate-button": duplicateButton,
    menus: menus,
    navigation: navigation,
    "preview-button": previewButton,
    sitemap: sitemap,
    "timezone-select": timezoneSelect,
  },
});
