---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'server/**'
      - 'config/**'
      - 'cypress/**'
      - 'cypress.config.js'
      - 'package.json'
      - 'next.config.mjs'
      - 'tsconfig.json'
      - 'streamarr-api.yml'
      - '.github/workflows/cypress.yml'
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'server/**'
      - 'config/**'
      - 'cypress/**'
      - 'cypress.config.js'
      - 'package.json'
      - 'next.config.mjs'
      - 'tsconfig.json'
      - 'streamarr-api.yml'
      - '.github/workflows/cypress.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    name: Cypress Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install and Enable Corepack
        run: npm install -g corepack --force && corepack enable
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 25
          cache: 'pnpm'
      - name: Setup cypress cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          install: false
          build: pnpm cypress:build
          start: pnpm start
          wait-on: 'http://localhost:3000'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_MIGRATIONS: true
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
