---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy API Docs

on:
  push:
    branches:
      - develop

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@81844d3a1f163bfd2439e712344d3aa26f87dd9d # v1
        with:
          output: swagger-ui
          spec-file: streamarr-api.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@e9c66a37f080288a11235e32cbe2dc5fb3a679cc # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          cname: api-docs.streamarr.dev
