name: Streamarr Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
      - name: Install and Enable Corepack
        run: npm install -g corepack --force && corepack enable
      - name: Ensure Yarn is correct version
        run: corepack prepare yarn@4.9.2 --activate
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  discord:
    name: Send Discord Notification
    needs: release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Job Status
        uses: technote-space/workflow-conclusion-action@v3
      - name: Combine Job Status
        id: status
        run: |
          failures=(neutral skipped timed_out action_required)
          status="$WORKFLOW_CONCLUSION"
          for failure in "${failures[@]}"; do
            if [ "$WORKFLOW_CONCLUSION" = "$failure" ]; then
              status="failure"
              break
            fi
          done
          echo "status=$status" >> "$GITHUB_OUTPUT"
      - name: Post Status to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.status.outputs.status }}
          title: ${{ github.workflow }}
          nofail: true
